name = "FASTX"
uuid = "c2308a5c-f048-11e8-3e8a-31650f418d12"
authors = [
    "Sabrina J. Ward <sabrinajward@protonmail.com>",
    "Jakob N. Nissen <jakobnybonissen@gmail.com>"
]
version = "1.3.0"

[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
BioGenerics = "47718e42-2ac5-11e9-14af-e5595289c2ea"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
BioSymbols = "3c28c6f8-a34d-59c4-9654-267d177fcfa9"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
Automa = "0.7, 0.8"
BioGenerics = "0.1"
BioSequences = "3"
BioSymbols = "5"
TranscodingStreams = "0.9.5"
julia = "1"

[extras]
FormatSpecimens = "3372ea36-2a1a-11e9-3eb7-996970b6ffbd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "FormatSpecimens"]
